aperture: [0, 390, 0, 422]
dualCam: 'yes'
monitor: {distance: 70, screen: 1, width: 28.5}
record: 'yes'
style: {fixLetterSize: 2.5, subtitleLetterSize: 0.7, textLetterSize: 1, titleLetterSize: 3,
  verbalColor: '#3EB4F0', wrapWidth: 16}
trigger: '5'
use_aperture: 'yes'
